<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-04-30 16:33

$extensionPath = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('directrequest');
return array(
	'tx_directrequest_manager' => $extensionPath . 'classes/class.tx_directrequest_manager.php',
);
